version: "3.9"

services:
  nuxt-app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0.0.0.0